# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'enter_your_license_key_here'
  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
#
# Agent Configuration:
#
agents:
  apachehttpd:
      hostname: httpd.apache.org
