# Please make sure to update the license_key information with the license key for your New Relic
# account.
#
newrelic:
  #
  # Update with your New Relic account license key:
  #
  license_key: 'YOUR_LICENSE_KEY_HERE'

  #
  # Set to '1' for verbose output, remove for normal output.
  # All output goes to stdout/stderr.
  #
  # verbose: 1
  #
# Agent Configuration:
#
# Enable "debug: true" to see metrics in stdout instead of sent to New Relic"
# Enable "extended_stats: true" to collect metrics from the human-readable server-status page"
# "hostport" can be left blank if port 80.
#
agents:
  apachehttpd:
      -
        hostname: www.yourserver.com
        hostport: 80
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
        testrun: false
        # Set "extended_stats: true" to parse stats from human-readable version of server-status
        extended_stats: true
      -
        hostname: httpd.apache.org
        hostport: 80
        # Set "debug: true" to see metrics in stdout instead of sent to New Relic"
        debug: false
        # Set "testrun: true" to use input from local text/html files. Only parses input once, then quits.
        testrun: false
        # Set "extended_stats: true" to parse stats from human-readable version of server-status
        extended_stats: true

